Classes
gonjavi/RubyTictactoe2 pull request #1
Opened 2019-08-08 19:31 UTC by gonjavi

This pull request is part of the previous pull request on a different repo, and this is the link of the previous: https://github.com/gonjavi/tictactoe/pull/1

2019-08-09 15:02 UTC, mosaaleb requested changes
## Nice work @gonjavi :clap:

### The implemented logic is right, the app works very well. But we have to improve  our app to be more modular (consist of small modules each doing only one thing).

- [ ] When you use `attr_accessor` in a class, this value can be changed from outside that class. So we need to change all our `attr_accessor` to `attr_reader` if it only needs to be changed from object created from that class.

- [ ] User interaction `puts`, `gets` commands should be in one executable file `main.rb`.

- [ ] There is a lot of styling guidelines errors in your code. Take a look at [rubyguidlines](https://github.com/rubocop-hq/ruby-style-guide) and please fix these errors.
You can install rubocop linter in your preferred code editor to catch errors once you wrote them. 
Another thing I see that you have already `.stickler` file but there is not checks here in this pull request, have you enabled the `stickler` for this repo. Here's a [reminder](https://github.com/microverseinc/linters-config/tree/master/ruby) 
![Screenshot from 2019-08-09 17-24-54](https://user-images.githubusercontent.com/4246637/62790110-a8395300-baca-11e9-94ab-53427e4ed6cc.png)


- [ ] Please, see my comments below.


DRY rules are very important for readability and also for future edits.

I hope that you will see OOP with different eye after you finish these requirements.

If you need any help or have any question contact me on slack (Muhammad Ebeid)

### Happy Coding :computer:

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/check_win.rb
> +                        end
- [ ] Game logic should have no `puts` and `get.chomp`, this comes from the single responsibility principle. From the name `check_win` should only check for wins, not to print. You can handle the user interactions like `put` and `get.chomp` in main. So this method now need to return either `true` or `false` and depending on the return value we can decide should we print any thing or continue playing.

This comes from the [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle). You can check by asking yourself what this method (or Class) do?. If you said the word "and" then this method does have more than one responsibility.

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/check_win.rb
> + class Check_win
`Check_win` and `Check_draw` classes can be refactored into single `Game` class which only responsibility is to check for game status. We can implement a method `end_game?` which returns true or false depending on the game status.
```ruby
def end_game?
  game_won? || game_drawn?
end
```
Then we can implement each method to either return false or true.

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/check_win.rb
> +        #checking each position in the array x inside winnig positions
We can also refactor `check_win` method to have three smaller methods
`horizontal_match || vertical_match || diagonal_match`
each one is responsible for checking just one case. This way we have broken big methods into much smaller methods.

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/check_win.rb
> +      [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]]
Instead of `@board = ["-", ......]` we already have a class for building the board. We can just say `@board = Board.new`. This way we are not separating the `board` object from the `game` object. As they already depend on each other.

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/check_draw.rb
> +                    z+=1
- **`[OPTIONAL]`** We can also refactor `check_draw` method. A drawn position is reached when all the cells are taken (meaning no cells with value "-").
So we can use 
`!board.any?("-")`
In addition to check that there is no cells with value `-` exist. I think we need also to check that the game is not won yet. Suppose a scenario where you checked a draw in a won position and all cells are taken.

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/turn.rb
> +class Turn
- [ ] **`[REQUIRED]`** The game logic should be kept in classes (no `put` or `get.chomp`)
This class is stuffed with a lot of logic that doesn't belong to this class. From the name of Turn class, it has to just swap turns, but:
- it checks if the input is number (**`[OPTIONAL]`** this logic should reside in board class as `valid_input?` method)
- it checks if the input has already been taken before (**`[OPTIONAL]`** this logic also needs to be in board class as `valid_cell?` method)
- **`[REQUIRED]`** it puts and gets input (this logic needs to be in the main class)

This way our code is more maintainable, as if you wanted to change any logic of any method in the future it will be much easier.

2019-08-09 15:02 UTC, mosaaleb commented on lib/classes/turn.rb
> +                    #continue to check board
I tried to input negative numbers from -1 to -9 and it worked. This need to be fixed.

2019-08-09 16:19 UTC, gonjavi commented on lib/classes/check_win.rb
> +                        end
can it return the winner?

2019-08-09 16:23 UTC, gonjavi commented on lib/classes/check_win.rb
> + class Check_win
is this mandatory?

2019-08-09 16:23 UTC, gonjavi commented on lib/classes/check_win.rb
> +        #checking each position in the array x inside winnig positions
is this mandatory?

2019-08-09 17:58 UTC, mosaaleb commented on lib/classes/check_win.rb
> + class Check_win
No, it's not. My point is that a class with the name `Car` create cars, `Game` starts game. But for `Check_win` and `Check_draw` it's kind of ambiguous what this class does especially you have method with the same name of the class.

2019-08-09 18:00 UTC, mosaaleb commented on lib/classes/check_win.rb
> +        #checking each position in the array x inside winnig positions
It's not but it's recommended.

2019-08-09 18:15 UTC, gonjavi commented on lib/classes/check_draw.rb
> +                    z+=1
ok

2019-08-09 18:25 UTC, gonjavi commented on lib/classes/check_win.rb
> + class Check_win
perfect, I understand, I will take it into account for future projects, because I have spent a lot time with this

2019-08-09 18:25 UTC, gonjavi commented on lib/classes/check_win.rb
> +        #checking each position in the array x inside winnig positions
ok ok

2019-08-09 18:49 UTC, mosaaleb commented
@gonjavi This is a collaborative project. Could you please tell me why you are working alone?

2019-08-09 21:33 UTC, gonjavi commented on lib/classes/check_win.rb
> +      [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]]
perfect I found the way

2019-08-09 22:02 UTC, gonjavi commented
I am working alone because, it is the best me, I spoke to Willow Mata about it

2019-08-09 22:09 UTC, gonjavi commented
I consider is ready for review, I don't know your real name to complete the form I chose the only Muhammad I found.

2019-08-10 04:38 UTC, maelfosso commented on lib/classes.rb
> +require_relative './classes/check_draw.rb'
Awesome!!

Nice application of ruby rules concerning separating the code.

2019-08-10 04:45 UTC, maelfosso commented
Hello,

Playing it's so simple, thank you for that nice experience. 

- [ ] **`[OPTIONAL]`** Please, could you indent your code? It will be more easy to read.

- [ ] **`[OPTIONAL]`** Please, could you clean your code? Removing comments.

# You can submit the project completion form and go to the next project.

Please, apply the **`[OPTIONAL]`** suggestion in your next project.
Thank you.

2019-08-10 04:46 UTC, gonjavi commented
perfect

2019-08-10 04:46 UTC, maelfosso approved these changes

2019-08-10 15:18 UTC, merged